export const portfolioLists = [
  {
    id: "1",
    title: "Green & Tasty Lemon",
    type: "Fruits",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p1.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
  {
    id: "2",
    title: "Organic Carrot",
    type: "Farmer",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p2.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
  {
    id: "3",
    title: "Organic Betel Leaf",
    type: "Leaf",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p3.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
  {
    id: "4",
    title: "Natural Tommato",
    type: "Fruits",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p4.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
  {
    id: "5",
    title: "Black Raspberry",
    type: "Farmer",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p5.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
  {
    id: "6",
    title: "Honey Orange",
    type: "Farmer",
    summary: "",
    description: "This is a portfolio 1",
    image: "/Images/portfolio/p6.png",
    contentImg: "",
    date: "",
    client: "",
    category: "",
    service: "",
  },
];
